# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sound.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sound.proto',
  package='sound',
  syntax='proto3',
  serialized_pb=_b('\n\x0bsound.proto\x12\x05sound\"\x14\n\x04Ping\x12\x0c\n\x04ping\x18\x01 \x01(\t\"\x14\n\x04Pong\x12\x0c\n\x04pong\x18\x01 \x01(\t\"\x1d\n\x0cSoundRequest\x12\r\n\x05sound\x18\x01 \x01(\x0c\"A\n\rSoundResponse\x12\r\n\x05\x61larm\x18\x01 \x01(\x08\x12\x0b\n\x03res\x18\x02 \x01(\t\x12\x14\n\x0ctagging_rate\x18\x03 \x01(\x02\x32`\n\x04\x46ile\x12\x33\n\x06\x44\x65\x66ine\x12\x13.sound.SoundRequest\x1a\x14.sound.SoundResponse\x12#\n\x07\x43onnect\x12\x0b.sound.Ping\x1a\x0b.sound.Pongb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='sound.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ping', full_name='sound.Ping.ping', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=42,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='sound.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pong', full_name='sound.Pong.pong', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=64,
)


_SOUNDREQUEST = _descriptor.Descriptor(
  name='SoundRequest',
  full_name='sound.SoundRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sound', full_name='sound.SoundRequest.sound', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=95,
)


_SOUNDRESPONSE = _descriptor.Descriptor(
  name='SoundResponse',
  full_name='sound.SoundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alarm', full_name='sound.SoundResponse.alarm', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='sound.SoundResponse.res', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tagging_rate', full_name='sound.SoundResponse.tagging_rate', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['SoundRequest'] = _SOUNDREQUEST
DESCRIPTOR.message_types_by_name['SoundResponse'] = _SOUNDRESPONSE

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'sound_pb2'
  # @@protoc_insertion_point(class_scope:sound.Ping)
  ))
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), dict(
  DESCRIPTOR = _PONG,
  __module__ = 'sound_pb2'
  # @@protoc_insertion_point(class_scope:sound.Pong)
  ))
_sym_db.RegisterMessage(Pong)

SoundRequest = _reflection.GeneratedProtocolMessageType('SoundRequest', (_message.Message,), dict(
  DESCRIPTOR = _SOUNDREQUEST,
  __module__ = 'sound_pb2'
  # @@protoc_insertion_point(class_scope:sound.SoundRequest)
  ))
_sym_db.RegisterMessage(SoundRequest)

SoundResponse = _reflection.GeneratedProtocolMessageType('SoundResponse', (_message.Message,), dict(
  DESCRIPTOR = _SOUNDRESPONSE,
  __module__ = 'sound_pb2'
  # @@protoc_insertion_point(class_scope:sound.SoundResponse)
  ))
_sym_db.RegisterMessage(SoundResponse)


# @@protoc_insertion_point(module_scope)
