# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sound_pb2 as sound__pb2


class FileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Define = channel.unary_unary(
                '/sound.File/Define',
                request_serializer=sound__pb2.SoundRequest.SerializeToString,
                response_deserializer=sound__pb2.SoundResponse.FromString,
                )
        self.Connect = channel.unary_unary(
                '/sound.File/Connect',
                request_serializer=sound__pb2.Ping.SerializeToString,
                response_deserializer=sound__pb2.Pong.FromString,
                )


class FileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Define(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Define': grpc.unary_unary_rpc_method_handler(
                    servicer.Define,
                    request_deserializer=sound__pb2.SoundRequest.FromString,
                    response_serializer=sound__pb2.SoundResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=sound__pb2.Ping.FromString,
                    response_serializer=sound__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sound.File', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class File(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Define(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sound.File/Define',
            sound__pb2.SoundRequest.SerializeToString,
            sound__pb2.SoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sound.File/Connect',
            sound__pb2.Ping.SerializeToString,
            sound__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
